### ISSUE TITLE
[Levelup] Bot can't handle Emoji as Role Icon when using !pf

### ISSUE THREAD

**Issue by emshov74** [vertyco/vrt-cogs#132]
**Describe the bug**
When using the !pf command on a user whose highest role with a role icon is a default emoji, the command returns an error instead of the requested profile.

**Cog Version***
Latest as of 7 sept 2023.

**To Reproduce**
1. Set a role with a default emoji (such as 😵‍💫) as it's role icon (Nitro Boost lvl 2 required);
2. Assign it to a user;
3. Request it's levelup cog profile using !pf [user]
4. See error prompt from the bot.

**Expected behavior**
A bot response with the Levelup profile of the requested user.

**Screenshots**
Screenshot of it giving the error response whilst 🍻was the role icon
![image](https://github.com/vertyco/vrt-cogs/assets/36211362/f36eae53-e01f-4cfe-b2af-1cc73cdbaeee)

Screenshot of it giving the profile when changing the role icon to a (custom) server emote
![image](https://github.com/vertyco/vrt-cogs/assets/36211362/00296b1c-edb9-4509-bd2b-2fb39d496aab)

**Comment by vertyco** [comment]
Could you please provide a traceback of the full error?

**Comment by emshov74** [comment]
_Please don't beat me for using Pterodactyl :(_

In embeds.0.footer.icon_url: Not a well formed URL.
[2023-09-07 22:25:24] [ERROR] red: Exception in command 'pf'
Traceback (most recent call last):
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/levelup/base.py", line 862, in get_profile
    + position
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/context.py", line 741, in reply
    return await self.send(content, reference=self.message, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/redbot/core/commands/context.py", line 91, in send
    return await super().send(content=content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/context.py", line 1024, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.footer.icon_url: Not a well formed URL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/levelup/base.py", line 864, in get_profile
    + str(percentage)
  File "/home/container/.local/lib/python3.11/site-packages/redbot/core/commands/context.py", line 91, in send
    return await super().send(content=content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/context.py", line 1024, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.footer.icon_url: Not a well formed URL.
# END OF LOG

**Comment by emshov74** [comment]
Hope you were able to recreate the error on your own :)

**Comment by vertyco** [comment]
I cannot reproduce this, and since Pterodactyl is not supported I won't be looking into it any further. Use a supported method of hosting the bot.
