### ISSUE TITLE
AutoDocs on python 3.10

### ISSUE THREAD

**Issue by PBOwner** [vertyco/vrt-cogs#190]
**Describe the bug**
Traceback (most recent call last):
  File "{HOME}/fb/lib/python3.10/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "{HOME}/.local/share/Red-DiscordBot/data/futurobot/cogs/CogManager/cogs/autodocs/autodocs.py", line 246, in makedocs
    if file.__sizeof__() > ctx.guild.filesize_limit:
AttributeError: 'NoneType' object has no attribute 'filesize_limit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/fb/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "{HOME}/.local/share/Red-DiscordBot/data/futurobot/cogs/CogManager/cogs/unknown/unknown.py", line 20, in on_command_error
    raise error
  File "{HOME}/fb/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/fb/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "{HOME}/fb/lib/python3.10/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'filesize_limit'

**Cog Version***
Latest

**To Reproduce**
1. run `[p]makedocs all` using python version 3.10
2. wait for outcome
3. error

**Expected behavior**
It will create the docs and send it

**Screenshots**

**Additional context**

**Comment by vertyco** [comment]
Fixed with version 1.0.2

**Comment by PBOwner** [comment]
Thank you

**Comment by PBOwner** [comment]
Also, I used a good portion of your code to make a feature where it will automatically create a Documentation Site, using the docs created with AutoDocs. If you want to check it out, etc, the code is here: https://github.com/PBOwner/PBCogs/blob/main/autodocsite/autodocsite.py
Would be worth checking out and maybe even making better
