### ISSUE TITLE
fluent cog issues

### ISSUE THREAD

**Issue by theMisteryDE** [vertyco/vrt-cogs#2]
Hey, I'm testing your fluent cog. When a channel is renamed, it will be shown in [p]fluent view, but if you try to remove it, the Bot responds that the channel isn't a fluent channel.
I tried what happens when I delete the channel. When I do the view command now I get an error:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/lady_red/cogs/CogManager/cogs/fluent/fluent.py", line 95, in _view
    name=discordchannel.name,
AttributeError: 'NoneType' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'name'

**Comment by vertyco** [comment]
Update your got the issue should be fixed now :)

**Comment by vertyco** [comment]
@theMisteryDE

**Comment by theMisteryDE** [comment]
worked! 
Really nice cog btw

**Comment by vertyco** [comment]
Thank you!
