### ISSUE TITLE
[Cartographer] Viewing settings errors if no settings have been set

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#212]
**Describe the bug**
Installing a fresh copy of the cog and running `[p]cartographerset view` will produce an error.

***Cog Version\***
1.1.7

**To Reproduce**
View bug description

**Expected behavior**
A user-friendly error that settings must be set, or a backup must be taken before viewing.

**Screenshots**
```py
Traceback (most recent call last):
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/red/.local/share/Red-DiscordBot/data/zm/cogs/CogManager/cogs/cartographer/main.py", line 262, in view_settings
    for guild_backup_folder in self.backups_dir.iterdir():
  File "/usr/lib/python3.11/pathlib.py", line 932, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/red/.local/share/Red-DiscordBot/data/zm/cogs/Cartographer/backups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/red/.local/share/Red-DiscordBot/data/zm/cogs/Cartographer/backups'
```

**Additional context**
I may be wrong about the underlying issue. Just assuming since no backup has been taken, the cog has not created a directory yet to store settings.

**Comment by vertyco** [comment]
fixed with 1.1.8, ty for providing enough detail to quickly patch this
