### ISSUE TITLE
[Tickets] Modal creation min/max comparison error

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#213]
**Describe the bug**
Looks to be an issue with the comparison between the minimum character and maximum character value

**Cog Version\***
2.9.6

**To Reproduce**
1. Create a modal for a panel
2. Set minimum characters req to 10
3. Set maximum characters req to 30

**Expected behavior**
Command should continue and set character requirements properly

**Screenshots**
```py
[2024-11-08 13:58:29] [ERROR] red: Exception in command 'tickets addmodal'
Traceback (most recent call last):
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/red/.local/share/Red-DiscordBot/data/zm/cogs/CogManager/cogs/tickets/commands/admin.py", line 419, in addmodal
    await self.create_or_edit_modal(ctx, panel_name, field_name)
  File "/home/red/.local/share/Red-DiscordBot/data/zm/cogs/CogManager/cogs/tickets/commands/admin.py", line 631, in create_or_edit_modal
    if max_length < minlength:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Additional context**
I reported this via DMs a while ago but had no proof as it never produced an error in the console, now it finally has.

**Comment by vertyco** [comment]
Fixed with version 2.9.8
