### ISSUE TITLE
[vrtutils] weird keyerror on `[p]getlibs`.

### ISSUE THREAD

**Issue by japandotorg** [vertyco/vrt-cogs#25]
So I've been getting this for some weird reason, no idea why tbh
```py
Traceback (most recent call last):
  File "[removed]", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "[removed]", line 128, in _getlibs
    packages = [str(p) for p in pkg_resources.working_set]
  File "[removed]", line 128, in <listcomp>
    packages = [str(p) for p in pkg_resources.working_set]
  File "[removed]", line 689, in __iter__
    yield self.by_key[key]
KeyError: 'jishaku'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[removed]", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "[removed]", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "[removed]", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'jishaku'
```

I'm using my own fork of jishaku which you can find @ https://github.com/japandotorg/jishaku

**Comment by vertyco** [comment]
I have removed this command since you can just to `[p]pip list` to get the same results

**Comment by vertyco** [comment]
Also fixing the underlying issue, thank you for reporting this
