### ISSUE TITLE
[NoBot] Error in viewing settings when all bots are not removed correctly

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#40]
Assuming this is because all bots within the settings have been kicked from the server and not removed from the cog itself before doing so.
```py
Traceback (most recent call last):
  File "/home/red/redenv/lib64/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/red/.local/share/Red-DiscordBot/data/modet/cogs/CogManager/cogs/nobot/nobot.py", line 92, in no_bot_view
    botlist += f"{botmember.mention}: {bot}\n"
AttributeError: 'NoneType' object has no attribute 'mention'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/redenv/lib64/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/redenv/lib64/python3.9/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/red/redenv/lib64/python3.9/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/redenv/lib64/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/red/redenv/lib64/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'mention'
```

**Comment by vertyco** [comment]
ty for reporting, this issue has been fixed with `26fd86f1`
