### ISSUE TITLE
[pixl] `ValueError` on pixlset image viewglobal cmd

### ISSUE THREAD

**Issue by Cool-aid-man** [vertyco/vrt-cogs#85]
**Describe the bug**
Command raised an exception: ValueError: item would not fit at row 1 (6 > 5 width)

**To Reproduce**
1. `.pixlset image viewglobal`
2. See the error

**Expected behavior**
Should show the global images that have been added to the bot

**Additional context**
> Traceback
```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/data/starship_main/cogs/CogManager/cogs/pixl/pixl.py", line 474, in view_global_images
    await self.image_menu(ctx, images, "Global Images")
  File "/home/ubuntu/data/starship_main/cogs/CogManager/cogs/pixl/pixl.py", line 743, in image_menu
    await menu(ctx, embeds, con, message=message, page=page)
  File "/home/ubuntu/data/starship_main/cogs/CogManager/cogs/pixl/menu.py", line 216, in menu
    m = MenuView(ctx, pages, controls, message, page, timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/data/starship_main/cogs/CogManager/cogs/pixl/menu.py", line 115, in __init__
    self.add_item(MenuButton(emoji, style))
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ui/view.py", line 326, in add_item
    self.__weights.add_item(item)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ui/view.py", line 112, in add_item
    raise ValueError(f'item would not fit at row {item.row} ({total} > 5 width)')
ValueError: item would not fit at row 1 (6 > 5 width)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1642, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
      File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1642, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: item would not fit at row 1 (6 > 5 width)
```

**Comment by vertyco** [comment]
fixed :)
