### ISSUE TITLE
Same as last report

### ISSUE THREAD

**Issue by mon5termatt** [vertyco/vrt-cogs#86]
```py
Exception during loading of package
Traceback (most recent call last):
  File "/data/venv/lib/python3.9/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.9/site-packages/redbot/core/bot.py", line 1680, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/cogs/CogManager/cogs/assistant/__init__.py", line 6, in <module>
    from .assistant import Assistant
  File "/data/cogs/CogManager/cogs/assistant/assistant.py", line 7, in <module>
    from .abc import CompositeMetaClass
  File "/data/cogs/CogManager/cogs/assistant/abc.py", line 7, in <module>
    from .models import DB, Conversations, GuildSettings
  File "/data/cogs/CogManager/cogs/assistant/models.py", line 6, in <module>
    from openai.embeddings_utils import cosine_similarity
  File "/data/cogs/Downloader/lib/openai/embeddings_utils.py", line 5, in <module>
    import plotly.express as px
ModuleNotFoundError: No module named 'plotly'

```

Seems to also require plotly

**Comment by vertyco** [comment]
added plotly to requirements info json, i guess the openai lib doesnt include those like its supposed to, just message me in the cog support server in my channel if theres another missing dependency
